# NumPy Basics 1
___

* standard convention to rename `numpy` to `np` when importing

In [1]:
import numpy as np

___

## NumPy Array
* Much faster and more memory efficient than Python list
* More optimized for arithmetic operations

In [2]:
# One-dimensional array
array_1d = np.array([3, 6, 10, 1, 2])
array_1d

array([ 3,  6, 10,  1,  2])

💡Tip: Run a cell with `?function_name` to get its docstring (documentation)

In [8]:
?np.array

Docstring:
array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.  This argument can only be used to 'upcast' the array.  For
    downcasting, use the .astype(t) method.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (

In [3]:
# Two-dimensional array
array_2d = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
array_2d * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [5]:
array_1d + array_1d

array([ 6, 12, 20,  2,  4])

* It's not possible to do arithmetic operations on arrays with different dimensions

In [6]:
array_1d + array_2d

ValueError: operands could not be broadcast together with shapes (5,) (2,3) 

In [15]:
# Array containing a million integers from 0 to 1,000,000
big_list = list(range(10 ** 6))
big_array = np.array(big_list)

* Simple speed comparison: multiply all elements by 5
* NumPy array is about 70 times faster
* Depending on the operation, it might be even faster

In [17]:
%timeit [i * 5 for i in big_list]
%timeit big_array * 5

73.7 ms ± 1.11 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.78 ms ± 7.54 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


___

### Array indexing
* One-dimensional array: similar to Python list
* Two-or-more-dimensional array: use comma to separate dimensions

In [11]:
big_array[:100]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### .shape
* return the dimensions of the array
* for example:
  * (5, ) means a one-dimensional array of 5 items
  * (2, 3) means a two-dimensional array of 2 rows and 3 columns

In [43]:
array_1d

array([ 3,  6, 10,  1,  2])

In [44]:
array_1d.shape

(5,)

In [45]:
array_2d.shape

(2, 3)

💡 use .ndim to return only the number of dimensions

In [46]:
array_1d.ndim

1

In [47]:
array_2d.ndim

2